/arm2/container_pick_coordinator:
  ros__parameters:
    grasp_offset_xyz_m:
    - -0.00126
    - 0.026693
    - -0.038555
    grasp_offset_rpy_deg:
    - -171.599
    - -1.234
    - 91.426
    reference_marker_yaw_deg: -74.24
    offsets_configured: true
