topdown:
  topic: /image_rect/compressed
  image_size:
  - 640
  - 480
  roi:
    x: 392
    y: 178
    width: 213
    height: 219
gripper_camera:
  device: /dev/video4
  image_size:
  - 640
  - 480
points:
- index: 1
  topdown_roi_pixel:
  - 191.0
  - 23.0
  topdown_image_pixel:
  - 583.0
  - 201.0
  gripper_pixel:
  - 499.0
  - 73.0
- index: 2
  topdown_roi_pixel:
  - 26.0
  - 20.0
  topdown_image_pixel:
  - 418.0
  - 198.0
  gripper_pixel:
  - 390.0
  - 389.0
- index: 3
  topdown_roi_pixel:
  - 13.0
  - 106.0
  topdown_image_pixel:
  - 405.0
  - 284.0
  gripper_pixel:
  - 127.0
  - 472.0
- index: 4
  topdown_roi_pixel:
  - 11.0
  - 196.0
  topdown_image_pixel:
  - 403.0
  - 374.0
  gripper_pixel:
  - 420.0
  - 348.0
- index: 5
  topdown_roi_pixel:
  - 134.0
  - 122.0
  topdown_image_pixel:
  - 526.0
  - 300.0
  gripper_pixel:
  - 487.0
  - 454.0
homography:
  topdown_roi_to_gripper_pixel:
  - - -4.5879636271
    - -3.2975334879
    - 412.0321849085
  - - -1.7993316327
    - -2.7792060499
    - 328.5796800373
  - - -0.0099388079
    - -0.0080033368
    - 1.0
  inlier_mask:
  - 1
  - 1
  - 1
  - 1
  ransac_threshold_px: 3.0
  reprojection_error_px:
    mean: 0.0
    max: 0.0
    per_point:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
