map:
  yaml: /home/jio/poter_ws/config/SLAM/current_map.yaml
  width: 207
  height: 113
  resolution: 0.01
  origin:
  - -0.198
  - -0.517
  - 0.0
  pgm_to_map_formula: map_x=origin_x+pgm_x*resolution; map_y=origin_y+(height-pgm_y)*resolution
topics:
  camera_image: /image_rect/compressed
  input_mode: direct_opencv_clicks
points:
- index: 1
  camera_pixel:
  - 83.0
  - 135.0
  pgm_pixel:
  - 5.667
  - 6.333
  map_xy:
  - -0.141333
  - 0.549667
- index: 2
  camera_pixel:
  - 78.0
  - 396.0
  pgm_pixel:
  - 6.667
  - 104.667
  map_xy:
  - -0.131333
  - -0.433667
- index: 3
  camera_pixel:
  - 590.0
  - 133.0
  pgm_pixel:
  - 202.333
  - 7.0
  map_xy:
  - 1.825333
  - 0.543
- index: 4
  camera_pixel:
  - 607.0
  - 407.0
  pgm_pixel:
  - 202.667
  - 104.333
  map_xy:
  - 1.828667
  - -0.430333
homography:
  camera_pixel_to_map_xy:
  - - 0.0042326414
    - 9.71329e-05
    - -0.5106430128
  - - 3.58868e-05
    - -0.0039750722
    - 1.1023327152
  - - 0.0001207403
    - 0.0001819434
    - 1.0
  inlier_mask:
  - 1
  - 1
  - 1
  - 1
  reprojection_error_m:
    mean: 0.0
    max: 0.0
    per_point:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
