map:
  yaml: /home/jio/poter_ws/config/SLAM/current_map.yaml
  width: 142
  height: 223
  resolution: 0.01
  origin:
  - -0.327
  - -3.731
  - 0.0
  pgm_to_map_formula: map_x=origin_x+pgm_x*resolution; map_y=origin_y+(height-pgm_y)*resolution
topics:
  camera_image: /camera/image_rect
  input_mode: direct_opencv_clicks
points:
- index: 1
  camera_pixel:
  - 88.0
  - 349.0
  pgm_pixel:
  - 42.333
  - 6.333
  map_xy:
  - 0.096333
  - -1.564333
- index: 2
  camera_pixel:
  - 576.0
  - 354.0
  pgm_pixel:
  - 6.667
  - 197.0
  map_xy:
  - -0.260333
  - -3.471
- index: 3
  camera_pixel:
  - 599.0
  - 97.0
  pgm_pixel:
  - 101.0
  - 216.667
  map_xy:
  - 0.683
  - -3.667667
- index: 4
  camera_pixel:
  - 79.0
  - 96.0
  pgm_pixel:
  - 137.667
  - 23.333
  map_xy:
  - 1.049667
  - -1.734333
homography:
  camera_pixel_to_map_xy:
  - - -0.0006589363
    - -0.003708016
    - 1.4425446346
  - - -0.0038214993
    - 0.0010858697
    - -1.5116497166
  - - 4.26493e-05
    - -0.0001854209
    - 1.0
  inlier_mask:
  - 1
  - 1
  - 1
  - 1
  reprojection_error_m:
    mean: 0.0
    max: 0.0
    per_point:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
